import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#adc6ff",
        surface: "#f7f9fb",
        "on-primary-fixed-variant": "#003ea8",
        "surface-bright": "#f7f9fb",
        "surface-container-high": "#e6e8ea",
        "surface-container-lowest": "#ffffff",
        outline: "#737686",
        "primary-container": "#2563eb",
        "secondary-container": "#dce2f3",
        "on-error-container": "#93000a",
        "surface-dim": "#d8dadc",
        "tertiary-container": "#0f69dc",
        "on-secondary-fixed": "#151c27",
        error: "#ba1a1a",
        "on-primary-container": "#eeefff",
        "outline-variant": "#c3c6d7",
        tertiary: "#0051b1",
        secondary: "#585f6c",
        "on-primary-fixed": "#00174b",
        "surface-container": "#eceef0",
        "surface-container-highest": "#e0e3e5",
        "secondary-fixed": "#dce2f3",
        "secondary-fixed-dim": "#c0c7d6",
        "surface-container-low": "#f2f4f6",
        "on-surface": "#191c1e",
        "primary-fixed-dim": "#b4c5ff",
        "on-tertiary-fixed": "#001a42",
        "on-secondary-container": "#5e6572",
        "on-primary": "#ffffff",
        primary: "#004ac6",
        "on-secondary-fixed-variant": "#404754",
        "surface-tint": "#0053db",
        "inverse-primary": "#b4c5ff",
        "on-background": "#191c1e",
        "on-secondary": "#ffffff",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        "on-tertiary-container": "#edf0ff",
        "error-container": "#ffdad6",
        background: "#f7f9fb",
        "on-tertiary-fixed-variant": "#004395",
        "on-error": "#ffffff",
        "primary-fixed": "#dbe1ff",
        "tertiary-fixed": "#d8e2ff",
        "surface-variant": "#e0e3e5",
        "on-surface-variant": "#434655",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "2xl": "48px",
        base: "8px",
        gutter: "24px",
        "container-max": "1200px",
      },
      fontFamily: {
        "label-sm": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "title-lg": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        sans: [
          "Plus Jakarta Sans",
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
        ],
      },
      fontSize: {
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0", fontWeight: "600" },
        ],
        "body-md": [
          "16px",
          { lineHeight: "24px", letterSpacing: "0", fontWeight: "400" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "0", fontWeight: "700" },
        ],
        "body-lg": [
          "18px",
          { lineHeight: "28px", letterSpacing: "0", fontWeight: "400" },
        ],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0", fontWeight: "500" },
        ],
        "title-lg": [
          "20px",
          { lineHeight: "28px", letterSpacing: "0", fontWeight: "600" },
        ],
        "display-lg": [
          "40px",
          { lineHeight: "48px", letterSpacing: "0", fontWeight: "700" },
        ],
        "headline-md": [
          "24px",
          { lineHeight: "32px", letterSpacing: "0", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
