import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./features/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    screens: {
      sm: "0px",
      md: "0px",
      lg: "0px",
      xl: "0px",
      "2xl": "1536px",
    },
    extend: {
      colors: {
        ink: "#111827",
        muted: "#667085",
        line: "#D7DDE5",
        canvas: "#F6F8FB",
        panel: "#FFFFFF",
        "panel-soft": "#EEF2F6",
        primary: "#2459E6",
        "primary-deep": "#163FAF",
        "primary-soft": "#E6ECFF",
        "cyan-soft": "#DFF6FF",
        "success-soft": "#ECFDF3",
        "success-text": "#047857",
        "warning-soft": "#FFF7E6",
        "warning-text": "#B45309",
        danger: "#E5484D",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#adc6ff",
        surface: "#F6F8FB",
        "on-primary-fixed-variant": "#163FAF",
        "surface-bright": "#F6F8FB",
        "surface-container-high": "#EEF2F6",
        "surface-container-lowest": "#ffffff",
        outline: "#667085",
        "primary-container": "#2459E6",
        "secondary-container": "#E6ECFF",
        "on-error-container": "#93000a",
        "surface-dim": "#D7DDE5",
        "tertiary-container": "#2459E6",
        "on-secondary-fixed": "#151c27",
        error: "#E5484D",
        "on-primary-container": "#ffffff",
        "outline-variant": "#D7DDE5",
        tertiary: "#2459E6",
        secondary: "#667085",
        "on-primary-fixed": "#00174b",
        "surface-container": "#EEF2F6",
        "surface-container-highest": "#D7DDE5",
        "secondary-fixed": "#E6ECFF",
        "secondary-fixed-dim": "#D7DDE5",
        "surface-container-low": "#F6F8FB",
        "on-surface": "#111827",
        "primary-fixed-dim": "#b4c5ff",
        "on-tertiary-fixed": "#001a42",
        "on-secondary-container": "#667085",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#404754",
        "surface-tint": "#2459E6",
        "inverse-primary": "#b4c5ff",
        "on-background": "#111827",
        "on-secondary": "#ffffff",
        "inverse-surface": "#111827",
        "inverse-on-surface": "#eff1f3",
        "on-tertiary-container": "#edf0ff",
        "error-container": "#ffdad6",
        background: "#F6F8FB",
        "on-tertiary-fixed-variant": "#004395",
        "on-error": "#ffffff",
        "primary-fixed": "#E6ECFF",
        "tertiary-fixed": "#d8e2ff",
        "surface-variant": "#EEF2F6",
        "on-surface-variant": "#667085",
      },
      borderRadius: {
        DEFAULT: "12px",
        lg: "16px",
        xl: "20px",
        "2xl": "20px",
        full: "9999px",
      },
      boxShadow: {
        card: "0 1px 2px rgba(16, 24, 40, 0.06), 0 8px 24px rgba(16, 24, 40, 0.06)",
        lift: "0 16px 40px rgba(16, 24, 40, 0.10)",
        nav: "0 1px 0 rgba(16, 24, 40, 0.08)",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "2xl": "48px",
        base: "8px",
        gutter: "24px",
        "container-max": "1200px",
      },
      fontFamily: {
        "label-sm": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "title-lg": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        sans: [
          "Plus Jakarta Sans",
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
        ],
      },
      fontSize: {
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0", fontWeight: "600" },
        ],
        "body-md": [
          "16px",
          { lineHeight: "24px", letterSpacing: "0", fontWeight: "400" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "0", fontWeight: "700" },
        ],
        "body-lg": [
          "18px",
          { lineHeight: "28px", letterSpacing: "0", fontWeight: "400" },
        ],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0", fontWeight: "500" },
        ],
        "title-lg": [
          "20px",
          { lineHeight: "28px", letterSpacing: "0", fontWeight: "600" },
        ],
        "display-lg": [
          "40px",
          { lineHeight: "48px", letterSpacing: "0", fontWeight: "700" },
        ],
        "headline-md": [
          "24px",
          { lineHeight: "32px", letterSpacing: "0", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
