import {
  parseAgentAction,
  AgentActionSchema,
  AgentActionRequiredTopLevelFields,
  AgentActionTopLevelFieldAllowlist,
  type AgentActionNormalizationDiagnostic,
  type AgentAction,
  type AgentRunInput,
  type TerminalOutputValidationSummary,
  type TerminalAgentAction,
  type ToolCallAction,
  type ToolManifest,
  type ToolResult,
} from "./contracts";
import { assertM0ExecutableTool } from "./define-tool";
import { AGENT_ERROR_CODES, AgentContractError } from "./errors";
import { validateConsumedResources } from "./resource-contract";
import type { ResourceStore } from "./resource-store";
import { projectSchemaValidationFeedback, type SchemaRepairTarget } from "./schema-error-projector";
import type { TerminalOutputValidatorRegistry } from "./terminal-output-validator";
import type { ToolRegistry } from "./tool-registry";
import type { ToolError } from "./contracts";

/** ActionValidationInput 汇总 validator 校验 action 所需的 registry、manifest 和本轮结果引用。 */
export type ActionValidationInput = {
  action: unknown;
  registry: ToolRegistry;
  manifests: ToolManifest[];
  toolResults: ToolResult[];
  run?: AgentRunInput;
  resourceStore?: ResourceStore;
  terminalOutputValidators?: TerminalOutputValidatorRegistry;
};

/** ActionValidationResult 用稳定 ToolError 表达 action 是否可执行。 */
export type ActionValidationResult =
  | { ok: true; action: AgentAction; terminalOutputValidation?: TerminalOutputValidationSummary; normalization?: AgentActionNormalizationDiagnostic }
  | { ok: false; error: ToolError; normalization?: AgentActionNormalizationDiagnostic };

/** validateAgentAction 在执行前校验 action 结构、tool 可用性、input schema 和 M0 resource 禁用边界。 */
export function validateAgentAction(input: ActionValidationInput): ActionValidationResult {
  return validateAgentActionInternal(input, "sync") as ActionValidationResult;
}

/** validateAgentActionAsync 支持业务 terminal output validator 在生产装配层异步读取事实。 */
export async function validateAgentActionAsync(input: ActionValidationInput): Promise<ActionValidationResult> {
  return validateAgentActionInternal(input, "async") as Promise<ActionValidationResult>;
}

function validateAgentActionInternal(
  input: ActionValidationInput,
  mode: "sync",
): ActionValidationResult;
function validateAgentActionInternal(
  input: ActionValidationInput,
  mode: "async",
): Promise<ActionValidationResult>;
function validateAgentActionInternal(
  input: ActionValidationInput,
  mode: "sync" | "async",
): ActionValidationResult | Promise<ActionValidationResult> {
  if (isPlannerGeneratedConfirmationRequest(input.action)) {
    return {
      ok: false,
      error: createToolError(
        AGENT_ERROR_CODES.CONFIRMATION_CLIENT_FORBIDDEN,
        "Confirmation requests can only be generated by server policy.",
      ),
    };
  }

  const candidate = normalizeAgentActionTopLevel(input.action);
  const parsed = parseAgentAction(candidate.action);

  if (!parsed.success) {
    return attachNormalization(
      invalidAction(createInvalidActionMessage(parsed.error), createInvalidActionDetails(parsed.error, candidate.action)),
      candidate.normalization ?? createNotNormalizableDiagnostic(input.action),
    );
  }

  const action = parsed.data;

  if (action.type === "tool_call") {
    return attachNormalization(validateToolCallAction(action, input), candidate.normalization);
  }

  if (mode === "async") {
    return Promise.resolve(validateTerminalAction(action, input, "async"))
      .then((result) => attachNormalization(result, candidate.normalization));
  }

  return attachNormalization(validateTerminalAction(action, input, "sync"), candidate.normalization);
}

const agentActionTopLevelFieldAllowlist = mapFieldAllowlists(AgentActionTopLevelFieldAllowlist);
type AgentActionTopLevelType = keyof typeof AgentActionTopLevelFieldAllowlist;
const plannerOwnedReferenceFields = new Set([
  "usedRefs",
  "usedToolResultIds",
  "usedResourceRefs",
  "consumes",
  "resourceId",
  "toolResultId",
  "factRef",
  "messageId",
  "resource",
]);

function normalizeAgentActionTopLevel(action: unknown): {
  action: unknown;
  normalization?: AgentActionNormalizationDiagnostic;
} {
  if (!isRecord(action) || !isAgentActionTopLevelType(action.type)) {
    return { action };
  }

  const selectedActionType = action.type;
  const allowedFields = agentActionTopLevelFieldAllowlist[selectedActionType];
  const unknownTopLevelKeys = Object.keys(action).filter((key) => !allowedFields.has(key));

  if (unknownTopLevelKeys.length === 0) {
    return { action };
  }

  if (unknownTopLevelKeys.some((key) => plannerOwnedReferenceFields.has(key))) {
    return { action };
  }

  const requiredFields = AgentActionRequiredTopLevelFields[selectedActionType];
  const hasRequiredTopLevelFields = requiredFields.every((field) => hasOwn(action, field));

  if (!hasRequiredTopLevelFields) {
    return { action };
  }

  // Normalization 只裁剪 selected variant 顶层无关字段，不能补齐 required field 或转换旧同义字段。
  const normalizedAction = Object.fromEntries(
    Object.entries(action).filter(([key]) => allowedFields.has(key)),
  );

  return {
    action: normalizedAction,
    normalization: {
      diagnosticStatus: "normalized",
      selectedActionType,
      droppedFields: unknownTopLevelKeys.map((key) => summarizeDroppedTopLevelField(key, action[key])),
    },
  };
}

function createNotNormalizableDiagnostic(action: unknown): AgentActionNormalizationDiagnostic {
  return {
    diagnosticStatus: "not_normalizable",
    selectedActionType: isRecord(action) && isAgentActionTopLevelType(action.type) ? action.type : undefined,
    droppedFields: [],
  };
}

function isAgentActionTopLevelType(value: unknown): value is AgentActionTopLevelType {
  return value === "tool_call" || value === "final_answer" || value === "ask_user";
}

function mapFieldAllowlists<T extends Record<string, readonly string[]>>(allowlists: T): {
  [K in keyof T]: ReadonlySet<string>;
} {
  const mapped = {} as { [K in keyof T]: ReadonlySet<string> };

  for (const type of Object.keys(allowlists) as Array<keyof T>) {
    mapped[type] = new Set(allowlists[type]);
  }

  return mapped;
}

function hasOwn(value: Record<string, unknown>, key: string) {
  return Object.prototype.hasOwnProperty.call(value, key);
}

function summarizeDroppedTopLevelField(path: string, value: unknown): AgentActionNormalizationDiagnostic["droppedFields"][number] {
  if (value === null) {
    return { path, valueType: "null" };
  }

  if (Array.isArray(value)) {
    return { path, valueType: "array", length: value.length };
  }

  if (typeof value === "string") {
    return { path, valueType: "string", length: value.length };
  }

  if (typeof value === "object") {
    return { path, valueType: "object", propertyCount: Object.keys(value as Record<string, unknown>).length };
  }

  return { path, valueType: typeof value };
}

function attachNormalization<T extends ActionValidationResult>(
  result: T,
  normalization: AgentActionNormalizationDiagnostic | undefined,
): T {
  return normalization ? { ...result, normalization } : result;
}

function validateToolCallAction(action: ToolCallAction, input: ActionValidationInput): ActionValidationResult {
  const tool = input.registry.get(action.toolName);
  if (!tool) {
    return {
      ok: false,
      error: createToolError(AGENT_ERROR_CODES.UNKNOWN_TOOL, `Tool "${action.toolName}" is not registered.`),
    };
  }

  const isVisible = input.manifests.some((manifest) => manifest.name === action.toolName);
  if (!isVisible) {
    try {
      assertM0ExecutableTool(tool);
    } catch (error) {
      if (error instanceof AgentContractError) {
        return {
          ok: false,
          error: createToolError(error.code, error.message),
        };
      }
      throw error;
    }

    return {
      ok: false,
      error: createToolError(
        AGENT_ERROR_CODES.UNSUPPORTED_M0_CAPABILITY,
        `Tool "${action.toolName}" is not available in the current M0 manifest.`,
      ),
    };
  }

  const inputResult = tool.inputSchema.safeParse(action.input);
  if (!inputResult.success) {
    return {
      ok: false,
      error: createToolError(
        AGENT_ERROR_CODES.INVALID_TOOL_INPUT,
        `Tool "${action.toolName}" input does not match its schema.`,
        projectSchemaValidationFeedback({
          target: {
            kind: "ToolInput",
            schemaId: `${tool.name}@${tool.version}.input`,
            toolName: action.toolName,
          },
          schema: tool.inputSchema,
          issues: inputResult.error.issues,
          value: action.input,
        }),
      ),
    };
  }

  const resourceValidation = validateConsumedResources({
    tool,
    action,
    resourceStore: input.resourceStore,
  });
  if (!resourceValidation.ok) {
    return {
      ok: false,
      error: resourceValidation.error,
    };
  }

  return { ok: true, action };
}

function validateTerminalAction(
  action: TerminalAgentAction,
  input: ActionValidationInput,
  mode: "sync",
): ActionValidationResult;
function validateTerminalAction(
  action: TerminalAgentAction,
  input: ActionValidationInput,
  mode: "async",
): Promise<ActionValidationResult>;
function validateTerminalAction(
  action: TerminalAgentAction,
  input: ActionValidationInput,
  mode: "sync" | "async",
): ActionValidationResult | Promise<ActionValidationResult> {
  if (action.type === "final_answer") {
    if (action.visibleOutputs?.length) {
      if (!input.terminalOutputValidators) {
        return {
          ok: false,
          error: createToolError(
            AGENT_ERROR_CODES.TERMINAL_REFERENCE_INVALID,
            "Final answer visibleOutputs require a terminal output validator registry.",
          ),
        };
      }

      const context = {
        action,
        run: input.run,
        toolResults: input.toolResults,
        resourceStore: input.resourceStore,
      };

      if (mode === "async") {
        return input.terminalOutputValidators.validateAll(action.visibleOutputs, context)
          .then((outputValidation) => {
            if (!outputValidation.ok) {
              return {
                ok: false as const,
                error: outputValidation.error,
              };
            }

            return {
              ok: true as const,
              action,
              terminalOutputValidation: outputValidation.summary,
            };
          });
      }

      const outputValidation = input.terminalOutputValidators.validateAllSync(action.visibleOutputs, context);
      if (!outputValidation.ok) {
        return {
          ok: false,
          error: outputValidation.error,
        };
      }

      return {
        ok: true,
        action,
        terminalOutputValidation: outputValidation.summary,
      };
    }
  }

  return { ok: true, action };
}

function invalidAction(message: string, details?: ToolError["details"]): ActionValidationResult {
  return {
    ok: false,
    error: createToolError(AGENT_ERROR_CODES.INVALID_ACTION, message, details),
  };
}

/** createToolError 将 validator/runtime 错误收敛成 renderer 可消费的 ToolError。 */
export function createToolError(code: ToolError["code"], message: string, details?: ToolError["details"]): ToolError {
  return {
    code,
    message,
    retryable: code === AGENT_ERROR_CODES.TIMEOUT || code === AGENT_ERROR_CODES.OVERALL_TIMEOUT,
    details,
  };
}

function isPlannerGeneratedConfirmationRequest(action: unknown) {
  return Boolean(
    action
      && typeof action === "object"
      && "type" in action
      && (action as { type?: unknown }).type === "request_confirmation",
  );
}

function createInvalidActionMessage(error: { issues: Array<{ path: PropertyKey[]; message: string }> }) {
  if (hasNumericVisibleOutputSchemaVersionIssue(error)) {
    return "Planner returned an action outside the M0 AgentAction contract: visibleOutputs[].schemaVersion must be a string.";
  }

  return "Planner returned an action outside the M0 AgentAction contract.";
}

function createInvalidActionDetails(
  error: { issues: Array<{ path: PropertyKey[]; message: string }> },
  action: unknown,
): ToolError["details"] {
  return projectSchemaValidationFeedback({
    target: createInvalidActionTarget(error, action),
    schema: AgentActionSchema,
    issues: error.issues,
    value: action,
  });
}

function hasNumericVisibleOutputSchemaVersionIssue(error: { issues: Array<{ path: PropertyKey[]; message: string }> }) {
  return error.issues.some((issue) => {
    const path = issue.path.map(String);
    return path[0] === "visibleOutputs"
      && path[path.length - 1] === "schemaVersion"
      && issue.message.includes("expected string");
  });
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value && typeof value === "object" && !Array.isArray(value));
}

function createInvalidActionTarget(
  error: { issues: Array<{ path: PropertyKey[]; message: string }> },
  action: unknown,
): SchemaRepairTarget {
  if (error.issues.length > 0 && error.issues.every((issue) => issue.path[0] === "visibleOutputs")) {
    const output = readFirstVisibleOutput(action);
    return {
      kind: "VisibleOutputEnvelope",
      schemaId: "VisibleOutputEnvelope",
      outputType: typeof output?.outputType === "string" ? output.outputType : undefined,
      variant: typeof output?.schemaVersion === "string" ? output.schemaVersion : undefined,
    };
  }

  return {
    kind: "AgentAction",
    schemaId: "AgentAction",
    ...(isRecord(action) && typeof action.type === "string" ? { variant: action.type } : {}),
  };
}

function readFirstVisibleOutput(action: unknown): Record<string, unknown> | undefined {
  if (!isRecord(action) || !Array.isArray(action.visibleOutputs)) {
    return undefined;
  }

  const [first] = action.visibleOutputs;
  return isRecord(first) ? first : undefined;
}
