import {
  parseAgentAction,
  type AgentAction,
  type AgentRunInput,
  type TerminalAgentAction,
  type ToolCallAction,
  type ToolManifest,
  type ToolResult,
} from "./contracts";
import { assertM0ExecutableTool } from "./define-tool";
import { AGENT_ERROR_CODES, AgentContractError } from "./errors";
import { validateConsumedResources } from "./resource-contract";
import type { ResourceStore } from "./resource-store";
import type { TerminalOutputValidatorRegistry } from "./terminal-output-validator";
import type { ToolRegistry } from "./tool-registry";
import type { ToolError } from "./contracts";

/** ActionValidationInput 汇总 validator 校验 action 所需的 registry、manifest 和本轮结果引用。 */
export type ActionValidationInput = {
  action: unknown;
  registry: ToolRegistry;
  manifests: ToolManifest[];
  toolResults: ToolResult[];
  run?: AgentRunInput;
  resourceStore?: ResourceStore;
  terminalOutputValidators?: TerminalOutputValidatorRegistry;
};

/** ActionValidationResult 用稳定 ToolError 表达 action 是否可执行。 */
export type ActionValidationResult =
  | { ok: true; action: AgentAction }
  | { ok: false; error: ToolError };

/** validateAgentAction 在执行前校验 action 结构、tool 可用性、input schema 和 M0 resource 禁用边界。 */
export function validateAgentAction(input: ActionValidationInput): ActionValidationResult {
  if (isPlannerGeneratedConfirmationRequest(input.action)) {
    return {
      ok: false,
      error: createToolError(
        AGENT_ERROR_CODES.CONFIRMATION_CLIENT_FORBIDDEN,
        "Confirmation requests can only be generated by server policy.",
      ),
    };
  }

  const parsed = parseAgentAction(input.action);

  if (!parsed.success) {
    return invalidAction(createInvalidActionMessage(parsed.error), createInvalidActionDetails(parsed.error));
  }

  const action = parsed.data;

  if (action.type === "tool_call") {
    return validateToolCallAction(action, input);
  }

  return validateTerminalAction(action, input);
}

function validateToolCallAction(action: ToolCallAction, input: ActionValidationInput): ActionValidationResult {
  if (action.consumes?.length && !input.resourceStore) {
    return {
      ok: false,
      error: createToolError(
        AGENT_ERROR_CODES.INVALID_RESOURCE_REFERENCE,
        "M0 does not consume resource references. ResourceStore belongs to M1.",
      ),
    };
  }

  const tool = input.registry.get(action.toolName);
  if (!tool) {
    return {
      ok: false,
      error: createToolError(AGENT_ERROR_CODES.UNKNOWN_TOOL, `Tool "${action.toolName}" is not registered.`),
    };
  }

  const isVisible = input.manifests.some((manifest) => manifest.name === action.toolName);
  if (!isVisible) {
    try {
      assertM0ExecutableTool(tool);
    } catch (error) {
      if (error instanceof AgentContractError) {
        return {
          ok: false,
          error: createToolError(error.code, error.message),
        };
      }
      throw error;
    }

    return {
      ok: false,
      error: createToolError(
        AGENT_ERROR_CODES.UNSUPPORTED_M0_CAPABILITY,
        `Tool "${action.toolName}" is not available in the current M0 manifest.`,
      ),
    };
  }

  const inputResult = tool.inputSchema.safeParse(action.input);
  if (!inputResult.success) {
    return {
      ok: false,
      error: createToolError(
        AGENT_ERROR_CODES.INVALID_TOOL_INPUT,
        `Tool "${action.toolName}" input does not match its schema.`,
      ),
    };
  }

  const resourceValidation = validateConsumedResources({
    tool,
    action,
    resourceStore: input.resourceStore,
  });
  if (!resourceValidation.ok) {
    return {
      ok: false,
      error: resourceValidation.error,
    };
  }

  return { ok: true, action };
}

function validateTerminalAction(action: TerminalAgentAction, input: ActionValidationInput): ActionValidationResult {
  if (action.usedResourceRefs?.length && !input.resourceStore) {
    return {
      ok: false,
      error: createToolError(
        AGENT_ERROR_CODES.INVALID_RESOURCE_REFERENCE,
        "M0 terminal actions cannot use resource references. ResourceStore belongs to M1.",
      ),
    };
  }

  if (action.usedResourceRefs?.length && input.resourceStore) {
    for (const ref of action.usedResourceRefs) {
      try {
        const resource = input.resourceStore.assertRegistered(ref);

        if (action.type === "final_answer" && resource.role !== "consumable") {
          return {
            ok: false,
            error: createToolError(
              AGENT_ERROR_CODES.TERMINAL_REFERENCE_INVALID,
              "Final answer cannot use diagnostic resources as successful grounding.",
              { resourceId: resource.resourceId, role: resource.role },
            ),
          };
        }
      } catch (error) {
        if (error instanceof AgentContractError) {
          return {
            ok: false,
            error: createToolError(error.code, error.message, error.details as ToolError["details"]),
          };
        }
        throw error;
      }
    }
  }

  const knownToolResults = new Map(input.toolResults.map((result) => [result.toolResultId, result]));
  const knownToolResultIds = new Set(knownToolResults.keys());
  const usedToolResultIds = action.usedToolResultIds ?? [];
  const unknownIds = usedToolResultIds.filter((id) => !knownToolResultIds.has(id));

  if (unknownIds.length > 0) {
    return {
      ok: false,
      error: createToolError(
        AGENT_ERROR_CODES.TERMINAL_REFERENCE_INVALID,
        "Terminal action references tool results that do not exist in the current run.",
        { unknownIds },
      ),
    };
  }

  // final_answer 只能引用已满足的成功 tool result，诊断或失败结果只能用于 ask_user/失败解释。
  if (action.type === "final_answer") {
    const unsatisfiedToolResultIds = usedToolResultIds.filter((id) => {
      const result = knownToolResults.get(id);
      return result ? !result.ok || !result.fulfillment.satisfied : false;
    });

    if (unsatisfiedToolResultIds.length > 0) {
      return {
        ok: false,
        error: createToolError(
          AGENT_ERROR_CODES.TERMINAL_REFERENCE_INVALID,
          "Final answer cannot use failed or unsatisfied tool results as successful grounding.",
          { toolResultIds: unsatisfiedToolResultIds },
        ),
      };
    }

    if (action.visibleOutputs?.length) {
      if (!input.terminalOutputValidators) {
        return {
          ok: false,
          error: createToolError(
            AGENT_ERROR_CODES.TERMINAL_REFERENCE_INVALID,
            "Final answer visibleOutputs require a terminal output validator registry.",
          ),
        };
      }

      const outputValidation = input.terminalOutputValidators.validateAll(action.visibleOutputs, {
        action,
        run: input.run,
        toolResults: input.toolResults,
        resourceStore: input.resourceStore,
      });
      if (!outputValidation.ok) {
        return {
          ok: false,
          error: outputValidation.error,
        };
      }
    }
  }

  return { ok: true, action };
}

function invalidAction(message: string, details?: ToolError["details"]): ActionValidationResult {
  return {
    ok: false,
    error: createToolError(AGENT_ERROR_CODES.INVALID_ACTION, message, details),
  };
}

/** createToolError 将 validator/runtime 错误收敛成 renderer 可消费的 ToolError。 */
export function createToolError(code: ToolError["code"], message: string, details?: ToolError["details"]): ToolError {
  return {
    code,
    message,
    retryable: code === AGENT_ERROR_CODES.TIMEOUT || code === AGENT_ERROR_CODES.OVERALL_TIMEOUT,
    details,
  };
}

function isPlannerGeneratedConfirmationRequest(action: unknown) {
  return Boolean(
    action
      && typeof action === "object"
      && "type" in action
      && (action as { type?: unknown }).type === "request_confirmation",
  );
}

function createInvalidActionMessage(error: { issues: Array<{ path: PropertyKey[]; message: string }> }) {
  if (hasNumericVisibleOutputSchemaVersionIssue(error)) {
    return "Planner returned an action outside the M0 AgentAction contract: visibleOutputs[].schemaVersion must be a string.";
  }

  return "Planner returned an action outside the M0 AgentAction contract.";
}

function createInvalidActionDetails(error: { issues: Array<{ path: PropertyKey[]; message: string }> }): ToolError["details"] {
  const issues = error.issues.map((issue) => ({
    path: issue.path.join("."),
    message: issue.message,
  }));

  if (!hasNumericVisibleOutputSchemaVersionIssue(error)) {
    return { issues };
  }

  return {
    issues,
    repair: "将 final_answer.visibleOutputs[].schemaVersion 改为字符串；具体版本值按 outputType 的模型可见合同和业务 validator 支持版本填写，不要输出数字，也不要让服务端替你转换。",
  };
}

function hasNumericVisibleOutputSchemaVersionIssue(error: { issues: Array<{ path: PropertyKey[]; message: string }> }) {
  return error.issues.some((issue) => {
    const path = issue.path.map(String);
    return path[0] === "visibleOutputs"
      && path[path.length - 1] === "schemaVersion"
      && issue.message.includes("expected string");
  });
}
